### PR TITLE
Set the selected language to i18n.locale so the app language changes.

### LINKED ISSUE #249: Feature
Mechanism to switch language when the app is open. Right now, with the current implementation, the language shown in the app is loaded when the app start and can't be changed afterwards.

This ticket don't cover the user interface, but just how things could be done behind the scenes to display a new language on the fly. Would be nice if userPreference (redux) could be store that new language preference but it's not mandatory.

### PR DESCRIPTION
**Pull request by hb2708**
✅ I have read the [contributing file](https://github.com/NMF-earth/nmf-app/blob/main/contributing.md)

## Summary

This PR Fixes #249
By Enabling app to show string based on user-selected language

## Changelog

Add call to set `i18n.locale` when user change language from language screen

## Demo

RPReplay_Final1635614236

### CODE REVIEW

**Comment by hb2708** [comment]
it's not very smooth mainly the add Emission -> Main category list does not show localized text.

**Review by PierreBresson — CHANGES_REQUESTED** [review]
Unfortunately, it doesn’t work.

**Comment by hb2708** [comment]
Yes agreed will need to find better way to let app reflect the language as perfectly as possible

**Comment by PierreBresson** [comment]
Closing for inactivity

**Pull request closed without merging**
