### PR TITLE
Translation management scripts

### PR DESCRIPTION
**Pull request by a2br**
Here are the translation management files requested in issue https://github.com/NMF-earth/nmf-app/issues/225 and started in PR https://github.com/NMF-earth/nmf-app/pull/231, now fully operational. They have all been tested and are ready to use.
### Changelog
Here is a recap of what has been changed in the following commits:
- `group-translation-files.js` has been created in `scripts/poeditor`. When executed, new JSON files will be created in the same dir for each language with all the corresponding translations in it (prettified with the native `JSON.stringify` function).
- `spread-translation-files.js` has been created in `scripts/poeditor`. When executed, the data in the JSON files created by the previous script will be copied into all the translation files across the repo.
- The scripts above have been executed (reference files created by `group~`, other files edited by `spread~` (indentation changed).
- a quick guide has been written in `README.md`

### CODE REVIEW

**Comment by a2br** [comment]
Excuse me @PierreBresson, could you please review the PR during the day? This is my last one in a Hacktoberfest-eligible repo, I hope I'll get the 4 PRs I need for the shirt...

**Review by PierreBresson — APPROVED** [review]
This time it works, beau travail!

**Comment by PierreBresson** [comment]
@a2br I've reassigned you to the task so you can get the t-shirt 👍
Merci beaucoup 👏

**Comment by a2br** [comment]
Mange tak, and happy Halloween! 🎃

**Comment by PierreBresson** [comment]
@a2br j'allais oublier: envoie moi ton adresse par mail à contact @ nmf . earth si tu veux les stickers cf #225 😉

**Pull request merged**
