### PR TITLE
Correct french translations

### PR DESCRIPTION
**Pull request by a2br**
## French translations improvements

I didn't find any code I could improve at the moment, so I corrected the translations to French (I'm a native speaker), plus 1 English translation, on a very small error about the `,` and the `.` in decimal numbers. I corrected blatant errors and more subtle ones in sentences that were grammatically correct but not very nice to read.

If you need me to explain my changes or some of them, I'll edit this message.

I would also like to add that I absolutely love this project, and strongly agree with the motivations and positions of NMF 💚
Keep up the great work!

### CODE REVIEW

**Comment by PierreBresson** [comment]
@a2br CI is failing, you need to update the tests with `yarn test -u`

Merci pour les corrections ;)

**Comment by a2br** [comment]
I updated the tests on my machine and committed the new code, but the tests fail on GitHub.
I changed the `test` property of `package.json` from `TZ=GMT jest` to `SET TZ=GMT && jest` though: after some researches on Internet, it seems like the original `test` field cannot work on Windows. Have I done something wrong?

**Comment by PierreBresson** [comment]
@a2br nope, not your fault, it's related to https://github.com/NMF-earth/nmf-app/issues/202
Don't know what to do about it yet...

**Comment by adamfitzgibbon** [comment]
@a2br yeah the way I deal with it is by just removing the time one piece of the test command and running the snapshot update. Then I discard the changes in the EmissionsList which changes based on time zone. That should fix your issue.

**Comment by a2br** [comment]
Well, since the tests are all passed on my machine, I don't really know what to do at this point. If anyone has an idea, please let me know.

**Note:** the PR mentioned above isn't this repo's n°1, but mine's, I made this to update my fork

**Comment by adamfitzgibbon** [comment]
@a2br all you need to do is undo your changes in the EmissionsList snapshot and commit using the ‘—no-verify’ option set so that it doesn’t prevent you from committing. The problem is that the server which is probably running in Linux correctly sets the time zone before running the tests but your local windows is not. So your machine thinks the snapshot passes since it matches your time zone but the GitHub server is running into GMT so it fails the comparison.

**Comment by a2br** [comment]
FINALLY, I'm done with that! 🎉 Thanks a lot, @adamfitzgibbon, I couldn't have figured out what was wrong without your help.

**Comment by PierreBresson** [comment]
@a2br @adamfitzgibbon we need to find a solution for this windows issue... thanks guys! 🤗

**Pull request merged**
