### PR TITLE
add bottomPadding[WIP]

### LINKED ISSUE #191: Tab bar text needs margin
Tab bar in the bottom of the screen needs to be improved : the text is too close to the OS navigation/controls. Instead we should have at least 4px of margin, between act and the bottom for e.g

signal-2020-10-09-122323

### PR DESCRIPTION
**Pull request by haohanyang**
fix #191 
image

### CODE REVIEW

**Comment by PierreBresson** [comment]
Looks wrong on ios
Screenshot 2020-10-09 at 15 50 24

**Comment by haohanyang** [comment]
Oh I ran it on my iPhone 8 and I didn't consider its effects on machines with straight bangs. I will try to fix it.

**Comment by hb2708** [comment]
@haohanyang @PierreBresson still open then i can take a look

**Comment by haohanyang** [comment]
@hb2708 I am currently busy. If you have worked it out and file a PR I will close this

**Comment by PierreBresson** [comment]
@hb2708 yes, go for it

**Pull request closed without merging**
