### PR TITLE
Fixed the unexpected line break in the imports group

### LINKED ISSUE #172: Re-organize imports on save
Would be nice to have something clean like this : 
```
import React from 'react';

import { PropTypes } from 'prop-types';
import styled from 'styled-components/native';

import ErrorImg from '../../assets/images/error.png';
import colors from '../../styles/colors';
```
See this [article](https://dev.to/otamnitram/sorting-your-imports-correctly-in-react-213m) for more info

### PR DESCRIPTION
**Pull request by hb2708**
✅ I have read the [contributing file](https://github.com/NMF-earth/nmf-app/blob/master/contributing.md)

## Summary

Fixes #172
issue where auto save -> Reformat add extra new line in the imports
 

## Changelog

Updated `newlines-between` to `always` as per https://dev.to/otamnitram/sorting-your-imports-correctly-in-react-213m

## Demo

On top of BudgetScreen.tsx, we have :

```
import React from "react";
import { ScrollView } from "react-native";
import { useSelector } from "react-redux";

import styles from "./BudgetScreen.styles";
import { Text, Button } from "../../components";

```

If changed it to the following :

```
import React from "react";
import { ScrollView } from "react-native";

import styles from "./BudgetScreen.styles";
import { useSelector } from "react-redux";
import { Text, Button } from "../../components";
```

And save the file, get the following :

```
import React from "react";
import { ScrollView } from "react-native";
import { useSelector } from "react-redux";

import styles from "./BudgetScreen.styles";
import { Text, Button } from "../../components";

```

Instead of :
```
import React from "react";
import { ScrollView } from "react-native";

import { useSelector } from "react-redux";

import styles from "./BudgetScreen.styles";
import { Text, Button } from "../../components";

```

### CODE REVIEW

**Comment by hb2708** [comment]
Okey so the above cases works but this case fails. 
image

**Comment by hb2708** [comment]
See this from the the [eslint doc](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#newlines-between-ignorealwaysalways-and-inside-groupsnever)
```
/* eslint import/order: ["error", {"newlines-between": "always-and-inside-groups"}] */
import fs from 'fs';

import path from 'path';

import index from './';

import sibling from './foo';
```

`always-and-inside-groups`
Is the culprit to give u the extra new line, and you get following output.

```
import React from "react";
import { ScrollView } from "react-native";

import { useSelector } from "react-redux";

import styles from "./BudgetScreen.styles";
import { Text, Button } from "../../components";
```

**Comment by PierreBresson** [comment]
@hb2708 : almost there. However, you need to have the CI working before merging like mentionned in the contributing file.

To do so:

- run `yarn lint:fix`
- place `/* eslint import/order:0 */` on top of the file so we can still have `/* SCREENS */`, `/* COMPONENTS */` etc...

**Review by PierreBresson — CHANGES_REQUESTED** [review]
See conversation

**Comment by hb2708** [comment]
@PierreBresson Thanks for confirming about the case above. Applied the changes and pushed. CI Checks are passed now

**Review by PierreBresson — APPROVED** [review]

**Comment by PierreBresson** [comment]
@hb2708 thanks for the changes :)

**Pull request merged**
