### PR TITLE
Add max width for chart container for big screens

### PR DESCRIPTION
**Pull request by BatDroid**
related to #111 
Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-10-11 at 00 29 50

### CODE REVIEW

**Comment by PierreBresson** [comment]
@BatDroid humm it looks like it's breaking the current design (see pictures below) 
Screenshot 2020-10-11 at 17 57 42
Screenshot 2020-10-11 at 17 58 30

**Comment by BatDroid** [comment]
I'm totally new to this app/repo. I can't see what is broken. could you explain it?

**Comment by PierreBresson** [comment]
@BatDroid no problem. If you have a look to the item total, transport, food, you will see that they are align center on your pr but not on master (cf screenshot that I've uploaded)

**Comment by BatDroid** [comment]
> @BatDroid no problem. If you have a look to the items `Total`, `Transport` and `Food` you will see that they are align center on your pr but not on master (cf screenshot that I've uploaded)
Thank you for the explanation here is the results:
Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-10-12 at 01 10 08
Simulator Screen Shot - iPhone 11 - 2020-10-12 at 01 11 00

**Comment by PierreBresson** [comment]
@BatDroid thank you!

**Comment by PierreBresson** [comment]
oneplus
Wrong rendering on android, revert changes

**Pull request merged**
