### PR TITLE
(add) displayName to createMock func, (fix) key prop to unic

### PR DESCRIPTION
**Pull request by Stanislavja**
✅ I have read the [contributing file](https://github.com/NMF-earth/nmf-app/blob/main/contributing.md)

### CODE REVIEW

**Review by PierreBresson — CHANGES_REQUESTED** [review]
CI is failing, probably need to update tests (`yarn test -u`)

**Comment by Stanislavja** [comment]
> CI is failing, probably need to update tests (`yarn test -u`)

problem in test for getEmissions selector

**Review by PierreBresson — APPROVED** [review]
Looks good 👍

**Comment by PierreBresson** [comment]
@Stanislavja thanks :)

**Pull request merged**
